# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFyoo19wDYxGqDhXie7nJrkGv3X5WU5D
"""

"""Want to write While loop and evaluate break statements """

while True:
  #Ask user for input until he enters an integer
  prompt = input ("Enter a senetence that you want me to reverse")
  if prompt.isdigit():
    break
  else:
    print(prompt[::-1]) #I keep forgetting this. Let me remember this

#Print all odd numbers up to a user-provided limit using while
num = int(input("Enter a number: "))
i = 1
while i <= num:
  if i % 2 !=0:
    print (i)
  i = i+1

"""
ATM Simulator: Loop until the user exits; supports balance check, withdraw, deposit
"""

while True:
  print ("This is an ATM Simulator. You can do the following operations:\n 1. Check Balance\n 2. Withdraw\n 3. Deposit\n 4. Exit")
  prompt = int (input ("Enter your choice: "))
  if prompt == 1:
    print ("Your balance is 10000")
  elif prompt ==2:
    amount= input(("Withdraw cash. Enter the Amount to withdraw"))
  elif prompt ==2:
    deposit = input("Enter the amount to deposit")
  else:
    break

"""Multiplication Table Generator	Ask the user for a number, generate its table using while"""
num = int (input ("Enter a number"))

iterator = 1

while iterator <=10:
  print (f"{num} * {iterator} = {num * iterator}\n")
  iterator = iterator+1

"""
Even Sum Accumulator	Keep asking for numbers, stop when 0 is entered. Then print sum of only evens
"""
i=0
eveny = 0
while True:
  num = int (input ("Keep entering numbers. Enter 0 to exit"))
  if num == 0:
    break
  else:

    if num % 2 == 0:
      eveny = eveny  + num

print (eveny)

#reverse counter
num = int(input("Enter a number"))
while num >0:
  print(num)
  num = num -1

