# -*- coding: utf-8 -*-
"""day08b_user_input_and_loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJKICLD-RW8ET6sIn8xPCgz6BZL6m8es
"""

"""
Accepting user input via input()


"""

#accept user input, type cast it to int(), and then check if it is a multiple of 10
div = int (input("Enter a number: "))
if div %10 == 0:
  print(f"{div} is divisible by 10")
else:
  print (f"{div} is Not divisible by 10")

"""While loop """
i=1
while i <= 5:
  print(i)
  i+= 1

#use while loop to accept user input until he/she says quit


message = ""
active = True
while message != "quit":
  #print ("This is a parrot program. Type 'quit' to exit")
  message = input("This is a parrot program. Type 'quit' to exit ")
  print (message)


""" The above program is simplistic but I will use boolean"""
active = True
while active:
  message = input("This a parrot program. Type 'quit' to exit")
  print (message)
  if message == "quit":
    active = False