# -*- coding: utf-8 -*-
"""day12_functions_and_list_mutation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15o67-50bD34_6hPvR6M7juGCPjDMSWYV
"""

"""Passing a list to the function """

def format_name(names):
  for name in names:
    print(f"Hello {name}")

names = ["Harish", "Vish", "Madhavi", "Kesava"]
format_name(names)

"""Modifying list in a function"""

#This function shall accept a list print the name, reverse it and print and deletes the item from the list and finally returns the empty list
names = ["Harish", "Vish", "Madhavi", "Kesava"]
def process_names(names):
 while names:
    name = names.pop(0)
    print(f"Hello {name} your reversed name is {name[::-1]}") #reverses the name
    #names.pop(0) #This deletes the first element in the list FIFO unlike the default behaviour of stack (LIFO)

process_names(names)
#delete_names(names)
print(names)

