# -*- coding: utf-8 -*-
"""day15_functions_args_kwargs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rSeJ6LUZB4NuJGpVFW8ItYCcp0lRhqt
"""

"""
Just to recap some function and concepts
"""

#default parameters

def profile_uppercase(name = "harish", age = 45):
  if isinstance(age, int):
    print(f"{name.upper()} is {age}")
  else:
    print(f"{age} is not a number")

profile_uppercase("Pradeep") #prints: PRADEEP is 45
profile_uppercase() #prints: HARISH is 45
profile_uppercase(age = 40) #prints: HARISH is 40 #I didn't realise I can do this
profile_uppercase("45", "Pradeep") #prints: PRADEEP is 45
profile_uppercase(age = 45, name = "PT usha") #when you do this kind of assignment the order does not matter
profile_uppercase()

#Return Factorial of number that is passed as an argument:
def factorial(n):
  if isinstance(n,int):
    if n<0:
      print ("Enter a positive number")
    elif n == 0:
      return 1
    else:
      iterator =1
      while n >= 1:
        iterator = iterator * n
        n= n- 1
      return iterator
  else:
        return n

print (factorial(5))

#Arbitrary arguments in a function
def user_profile(first, last, **profile):
  profile["First_Name"] = first
  profile["Second_Name"] = last
  return profile

   #creates a dictionary called profile
print (user_profile("Harish", "Puvvula", location = "Vuyyuru", age = 45, sex = "male" ))
print (user_profile("Pradeep", "Puvvula", Occupation = "Owner", Business = "Education"))

#Make Sandwhich. The funnction should collect all the ingredients a customer needs in his sandwhich and prints the summary of the ingredients
def make_sandwhich(*ingredients):
  print ("-------------The Sandwich Summary-----------------")
  i = 0
  for ingredient in ingredients:
    i = i+1
    print (f"{i}. {ingredient}")
  i=0

make_sandwhich("Chicken Ham", "Salami", "Lyoner", "Brocolli")