# -*- coding: utf-8 -*-
"""day16_arbitrary_kwargs_and_unpacking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t543VIezsc_XstPn_ii2Kv6avnD0SqJ4
"""

""" Arbitary Keyword Recap"""
def manyuseit(first, last, **profile):
  profile["first"] = first
  profile["last"] = last
  print (type(profile))

print((manyuseit("Haris", "Puvvula", location="Vyr", Age = 45)))

"""Storing functions in files"""