# -*- coding: utf-8 -*-
"""day10_while_loops_and_input_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RaKNIbRgdP9PEUfcYuLLa4CfNNeLOl4
"""



"""
Using while loops in lists to copy one list to the other
"""
my_family = ["Harish", "Shilpa", "Kiaan", "Mom", "Pradeep", "Aruna"]

bro_family = []

while my_family:
    bro = my_family.pop()
    bro_family.append(bro)
bro_family.reverse()
print(bro_family)


####Removing all instance of an item from the list

test_list = ["Harish", "Kesava", "Harish", "Vish", "Abhishek", "Kunal"]
while "Harish" in test_list:
    test_list.remove("Harish")
print(test_list)


###Using while loop to populate Dictionary

polling = 1
mountains = {}

while polling:
  name = input ("Enter your name")
  mountian = input ("whihc mountian would you climb")
  mountains[name] = mountian
  polling = int(input("Enter 1 to continue 0 to exit"))
  if polling == 0:
    break
print(mountains)

"""🎯 Goal:
Ask the user to enter names one by one. Separate names into two lists based on a simple rule:

If the name starts with a vowel → go to vowel_names

Else → go to consonant_names

Keep looping until they type 'done'.

🧠 Requirements Recap:
Use a while loop

Use .lower() to make checks case-insensitive

Use .startswith() for checking vowels

End loop when user types "done"

"""

vowel_names = []
consonant_names = []

while True:
    names = input("Enter a name: ")
    names = names.lower()

    if names == "done":
        break

    vowels = ["a", "e", "i", "o", "u"]
    first_letter = names[0]

    if first_letter in vowels:
        vowel_names.append(names)
    else:
        consonant_names.append(names)

print("Vowel Names:", vowel_names)
print("Consonant Names:", consonant_names)

###Grocery List ####
grocery_list = []

while True:
  item = input ("Enter the item")
  if item[0] == "remove":
    grocery_list.remove(item)
  elif item == "checkout":
    break
  else:
    grocery_list.append(item)

