# -*- coding: utf-8 -*-
"""day16b1_pizza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doKycGNaZL4AwVN3T9WTLnW_otaKpI17
"""

"""Will use functions in this file to be called in other files"""
""" This file will be a clone of Makepizza.py file made yesterday. I am going to try function calls with same names from two different modules"""
import pizza #importing pizza.py which is in the same directory as this file
#from pizza import *
from pasta import *
from pizza import *
pizza.make_pizza(16, "Pepperoni") #moduel.functionname() notation
pizza.make_pizza(24, "pepperoni", "mushrooms")
deliver("Harish") #both Pizza.py and pasta.py have function with the same name
""" 
In the above case why is pizza taking a precedence???
Apparently the order matters here.. I have imported Pizza last hence overwritten the one from pasta.py.
The best method is to use module.function() nomenclature.
"""
import pizza as pz #using aliases
import pasta as pt
pt.deliver("Harish") #invokes function in pasta.py
pz.deliver("Harish") #invokes function in pizza.py 
pt.seek_feedback() #will throw error because I have not imported the function





