# -*- coding: utf-8 -*-
"""day18_class_basics_automobile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10w2R_XaYuSjxOuoUBy1HSpFuxll2p3Bl
"""

"""
Class definitions - first tryst with classes
"""
#automobile class it has the type(car, lorry, bus), it has wheels, and it moves and honks horn

class Automobile:
  def __init__(self, type, wheels):
    self.type = type
    self.wheels = wheels
    print (f"I have been created with {self.wheels} wheels and I am a {self.type}")
  def move(self):
    print(f"{self.type} moves on {self.wheels} wheels")
  def honks(self):
    print(f"{self.type} honks")

car = Automobile("car", 4)
car.move()
car.honks()
print(car.wheels)

lorry = Automobile("Lorry", 6)