# -*- coding: utf-8 -*-
"""day23_composition_check_engine_status.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QP2uNRJEMw8ZlvHAejMNzpCEv4o-CZoY
"""

"""
Baby steps to composition

"""

#Engine Class
class Engine:
  def __init__(self, horsepower):
    self.horsepower = horsepower
    self.status = "off"

  def start(self):
    self.status = "on"
    print (f"Engine has started with {self.horsepower} horsepower")

  def stop(self):
    self.status = "off"
    print ("Engine has stopped")

class Car:
  def __init__(self, brand, horsepower):
    self.brand = brand
    self.engine = Engine(horsepower)

  def start(self):
    self.engine.start()
    print (f"Car {self.brand} has started")

  def stop(self):
    self.engine.stop()
    print (f"Car {self.brand} has stopped")
  def check_engine_status(self):
    return self.engine.status

my_car = Car("Toyota", 200)
my_car.start()
my_car.stop()

