# -*- coding: utf-8 -*-
"""day24_multi_class_composition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UA91sj-VOrd3mYHb3kAkSEvVaqBIjglV
"""

""" Continutaion of multi-class composition"""
class Engine:
  def __init__(self, horsepower, capacity):
    self.horsepower = horsepower
    self.capacity = capacity
    self.status = "off"
  def start(self):
    self.status = "on"
  def stop(self):
    self.status = "off"


class GPS:
  def __init__(self, current_location, destination):
    self.current_location = current_location
    self.destination = destination
  def set_destination(self,destination):
    print("We are all set to leave to {destination}")
  def get_eta(self, destination):
    print(f"we are all set to reach the {destination} in X minutes ")

class Car:
  def __init__(self, model, horsepower, capacity, current_location, destination):
    self.engine = Engine(horsepower, capacity)
    self.gps = GPS(current_location, destination)
    self.model = model
  def start_car(self):
    if self.engine.capacity > 0:
      self.engine.start()
    else:
      print("Engine is off")
  def set_trip(self, destination):
    self.gps.set_destination(destination)
  def refuel_car(self, amount):
    if amount > 0:
      self.engine.capacity += amount
    else:
      print("Invalid amount")

  def drive(self):
    if self.engine.status == "on":
      self.gps.get_eta(self.gps.destination)

my_car = Car("Maruthi Zen", 1400, 25, "Hyderabad", "Vuyyuru" )
my_car.refuel_car(50)
my_car.start_car()
my_car.set_trip("Vuyyuru")
my_car.drive()