# -*- coding: utf-8 -*-
"""day29_even_sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKOCna9bFxuqfY0H4V1AsdX-2PH9oSeJ
"""

"""
Write a Python program that asks the user for a positive integer n and calculates the sum of all even numbers from 1 to n (inclusive).
Print the result.

"""
number = int(input("Enter the number"))
summy = 0
list_even = [ x for x in range(2,number+2,2)]
print (list_even)
for x in list_even:
  summy = summy + x
print(summy)