# -*- coding: utf-8 -*-
"""day37_string_oneliners.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNKY8t9-Bw6An_yfZoB9enmD6KGC4V7M
"""

""" Some more python onliners"""
my_string = "harish is a good man"
print(my_string[::-1])
print(my_string[::2])