# -*- coding: utf-8 -*-
"""day35_scatter_plot_with_color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHl6n-FNQKoGQ1cRjCFKH2Gloo5VapOp
"""

# day34_scatter_plot.py
import matplotlib.pyplot as plt

x = [i for i in range(1, 21)]
y = [i**2 for i in x]

# color = value, size = cube
colors = [i for i in x]
sizes = [i**1.5 for i in x]

fig, ax = plt.subplots()
scatter = ax.scatter(x, y, c=colors, s=sizes, cmap='viridis', alpha=0.7, edgecolors='k')

ax.set_title("Day 34: Scatter Plot with Color & Size Mapping")
ax.set_xlabel("Value")
ax.set_ylabel("Square")

# add colorbar to show mapping
plt.colorbar(scatter, label="X Value")

plt.show()