# -*- coding: utf-8 -*-
"""day33_plot_reinforcement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFKyZC6OjvrarEU_7MBEAAMBN00Ir3qk
"""

"""Day 33 of plotting graphs"""
from matplotlib import pyplot as plt
list2 = [2,4,9,16,25,36,49,64,81,100]
list3 = [x ** 3 for x in range (1,11)]
fx,ax = plt.subplots()
ax.plot(list2,list3,linewidth = 1)
ax.set_title("Cubic Numbers")
ax.set_xlabel("Value")
ax.set_ylabel("Cube of Value")
plt.show()

"""ax.plot(list3)
ax.set_title("Cubic Numbers")
ax.set_xlabel("Value")
ax.set_ylabel("Cube of Value")
plt.show()"""