# -*- coding: utf-8 -*-
"""day31_first_plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9LcacJfI0Ce-sYYzXqccxDWr0qRMte1
"""

"""First at plotting graphs"""

import matplotlib.pyplot as plt

mylist = [x ** 2 for x in range(0, 100, 2)]

fig, ax = plt.subplots()
ax.plot(mylist)

plt.show()