# -*- coding: utf-8 -*-
"""day36_oneliner_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7-RbOPlPO7Wqp20-KO0pz9XJop8jBT7
"""

"""
Practice oneliners

"""

#comprehensions
empty_tuple = {}
empty_tuple= [ {x,y} for x in range(3) for y in range(3)] #this could be tuple, list, set change the [, (, }
print(empty_tuple)

#strings
print([x.lower() for x in "harish is a goodd boy"])

#dictionary
employees = {"Alice":100000, "Bob":99817, "Carol":122908, "Frank": 88123, "Eve":93121}
#find the highest earner
high_earner = [(x,y) for x,y in employees.items() if y>= 100000]
print(high_earner)