# -*- coding: utf-8 -*-
"""day34_scatter_squares_cubes.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xsZkKQXatskOkfGCYrgAMsve3YjgvVg
"""

"""
day 3 of graphs
Using scatter and other styles
"""

import matplotlib.pyplot as plt
x_values = [1,2,3,4,5,]
y_values = [1,4,9,16,25]
plt.style.use('seaborn-v0_8')
fg,ax = plt.subplots()

plt.scatter(x_values,y_values,s=100)
ax.set_title("Square Numbers",fontsize=24)
ax.set_xlabel("Value",fontsize=14)
ax.set_ylabel("Square of Value",fontsize=14)

"""
Day 3 of Graphs
Using scatter and other styles
"""

import matplotlib.pyplot as plt

x_values = [1, 2, 3, 4, 5]
y_values = [1, 4, 9, 16, 25]

# Try different styles here: seaborn-v0_8, ggplot, fivethirtyeight, classic...
plt.style.use('seaborn-v0_8')

fig, ax = plt.subplots()

# Scatter plot with custom color and edge
ax.scatter(x_values, y_values, s=100, c='red', edgecolor='red')

# Labels and title
ax.set_title("Square Numbers", fontsize=20, fontweight='bold')
ax.set_xlabel("Value", fontsize=14)
ax.set_ylabel("Square of Value", fontsize=14)

# Adjust tick size
ax.tick_params(axis='both', which='major', labelsize=12)

plt.show()