# -*- coding: utf-8 -*-
"""day39_StreakCheat2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjbz4-zkWgNJL9EeF-0Ya6tjXWP6Bwjw
"""

"""
Managing a streak
"""

print("Putting up streak 2")