# -*- coding: utf-8 -*-
"""day32_matplotlib_graph_legends_details.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSPYpSYZ1zSVaF9KsoN-NPBeGz11n-gv
"""

"""
Further exploring of Python plottin

"""

from matplotlib import pyplot as plt

mylist1 = [2,4,6,8,10,12,14,16,18]
mylist2 = [X ** 3 for X in range(1,200,2)]
fig,ax = plt.subplots()
#ax.plot(mylist1, label ="x2")
ax.plot(mylist2, label = "x3", linewidth=1)
ax.set_title("Cube Graph")
ax.set_xlabel("Value")
ax.set_ylabel("Cube")
ax.legend()
plt.show()

##i want to create another graph