# -*- coding: utf-8 -*-
"""day45_streak_preserve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlgNpQreyiu39D4H8t6m68jL3l4KySHP
"""

print("Just preserving my streak")