# -*- coding: utf-8 -*-
"""day44_one_liners4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKlFbYPrnmCSbvoYCQXBT887psw9dD2u
"""

#Python code to flatten nested sublists
nested = [[1,2],[3,4], [5,6],[7,8], [9.10]]
[x for sub in nested for x in sub]

#this is litreally an aha momen for me

