# -*- coding: utf-8 -*-
"""day42_one_liners2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ov9DPqaT1rE6WtdmsxdJcNVUkviCWlZO
"""

#Onliners in Python

#Find all the even numbers in given range using oneliners

number = int(input("Enter an integer"))
even_list = [x for x in range(1,number) if x % 2 == 0]
print(even_list)

#check is a string is a palindrome
my_string  = input("Enter a string")
print(my_string == my_string[::-1])

# Oneliner for factorial
import math
print(math.factorial(int(input("Enter a number"))))
#This is unique I didn't relalise we can call functions like this

#Square all numbers till a given range
print(list(x**2 for x in range(1, int(input("Enter a number"))+1)))

