# -*- coding: utf-8 -*-
"""day46_streak

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ackxVi-4yzKosHWBDizgklFUKyLSaofx
"""



print("preserving my streak" )