# -*- coding: utf-8 -*-
"""day48_onliners5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zDUIXg5ZEiX65V3AvuHtc2ydoHkgGAn
"""

"""Extract digits from a string """

print([int(ch) for ch in "abc123xyz456" if ch.isdigit()])
print (set ([ch for ch in "abc123xyz456" if not (ch.isdigit())]))
#print ([int(ch) for ch in "abc123xyz456" if ch.isdigit()