# -*- coding: utf-8 -*-
"""day43_one_liners3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzHxoA73Tn5LXqFYYCmq6byZfnc80PdM
"""

""" A few more onliners"""
#get the square of only odd numbers
n= int(input("Enter a number"))
print([ x**2 for  x in range(1,n) if x % 2!=0])

#Find all unique charachters in a string
print(set("harish"))