# -*- coding: utf-8 -*-
"""day41_streak.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHleP8HBHP3MivEEIPdI0cnSxym0_fS4
"""

print ("Just keeping the streak alive. Missed the previous day")