# -*- coding: utf-8 -*-
"""day50_conditional_assignment_oneliner.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6qf9JUvmYhv2dA4miep_gPM7mLJ56rC
"""

age = 20
status = "adult" if age >= 18 else "minor"