# -*- coding: utf-8 -*-
"""day16b1_pizza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doKycGNaZL4AwVN3T9WTLnW_otaKpI17
"""

"""Will use functions in this file to be called in other files"""
import pizza #importing pizza.py which is in the same directory as this file
from pizza import *
pizza.make_pizza(16, "Pepperoni") #moduel.functionname() notation
pizza.make_pizza(24, "pepperoni", "mushrooms")
deliver_pizza("Harish") #since imported the function I don't have to use module.function_name()
seek_feedback() #will throw error because I have not imported the function


