# -*- coding: utf-8 -*-
"""day16b1_pizza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doKycGNaZL4AwVN3T9WTLnW_otaKpI17
"""

"""Will use functions in this file to be called in other files"""
def make_pasta(color, *toppings):
  print(f"Making {color} pasta with these toppings")
  for topping in toppings:
    print(f"- {topping}")
    
def deliver(name):
   address = input ("Enter the address of delivery")
   print(f"The pasta for {name} must to be delivered to {address}")
   
def seek_feedback():
    rating = input("Please share your feedback for pasta: 1- 5")
    print (rating)
 